config/routes.rb
Myflicks::Application.routes.draw do

  get "all_flicks/index"
  get "your_flicks/index"
  get "home/index"  

  resources :all_flicks
  resources :flicks
  resources :imdb_data
  resources :your_flicks
  resources :user_comments
  devise_for :users
  resources :users

  root 'home#index'

  

end

app/models/all_flick.rb
class AllFlick < ActiveRecord::Base
end

app/controllers/all_flicks_controller.rb
class AllFlicksController < ApplicationController
  def index
    if !user_signed_in?
      redirect_to root_url, notice: "You must be signed in to access other pages!"
    else
      if params[:search]
        all_user_flicks = ImdbDatum.search(params[:search]).order("created_at DESC")
      else
        all_user_flicks = Flick.all # All flicks in Flick table
      end

        @active_flicks_data = Array.new # Store imdb_data of active flicks
        @current_user_list = Array.new # Flicks in current user's list

        all_user_flicks.each { |f|
          begin
            # Fetch data for active flicks
            active_flicks_by_users = ImdbDatum.find(f.imdb_id) 
            if active_flicks_by_users
              @active_flicks_data.push(active_flicks_by_users) # Populate active_flicks array to print flicks on index
            end
      
            # Show quick_add_button only if user doesn't have the flick in their list
            if f.user_id == current_user.id
              @current_user_list.push(active_flicks_by_users.imdb_id)
            end
          rescue
            next
          end
        }
        @active_flicks_data.uniq! # Remove duplicate entries, if any exist
    end  
  end
end

app/helpers/all_flicks_helper.rb
module AllFlicksHelper
end

app/views/all_flicks/_form.html.erb
<%= form_for(@all_flick) do |f| %>
  <% if @all_flick.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@all_flick.errors.count, "error") %> prohibited this all_flick from being saved:</h2>

      <ul>
      <% @all_flick.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/all_flicks/edit.html.erb
<h1>Editing all_flick</h1>

<%= render 'form' %>

<%= link_to 'Show', @all_flick %> |
<%= link_to 'Back', all_flicks_path %>

app/views/all_flicks/index.html.erb
<div class="main_body">
<br />
<br />
<% flick_count = @active_flicks_data.count %>
<span class="sub_heading">All Flicks (<%= flick_count %>)</span>
  <%= form_tag(all_flicks_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search by title or year" %>
  <% end %>
<br />
<br />
  
  <% if flick_count > 0 %>
      <% @active_flicks_data.each do |imdb_datum| %>
          <div class="well">
            <div id="poster_index"><img src="<%= imdb_datum.poster %>" /></div>

            <div id="flick_title">
              <a href="<%= imdb_datum_path(imdb_datum.imdb_id) %>"><%= imdb_datum.title %> (<%= imdb_datum.year %>)</a>
            </div>
            <div id="index_flick_options"> 
              <span class="icon-comment"></span>
              <% comment_count = imdb_datum.user_comments.count %>
              <span><a href="<%= imdb_datum_path(imdb_datum.imdb_id) %>#comments_section">Comments (<%= comment_count %>)</a></span>
              <% if !@current_user_list.include? imdb_datum.imdb_id %>
                <br />
                <br />
                <span class="icon-film"></span>
                <%= link_to 'Add To myFlicks', new_flick_path(:imdb_id => imdb_datum.imdb_id) %>
              <% end %>
              <% if current_user.admin? %>
                <br />
                <br />
                <span class="icon-remove"></span>
                <%= link_to "Remove (Admin)", imdb_datum, method: :delete, data: { confirm: 'Are you sure?' }, id: "admin_option" %>
              <% end %>
            </div>
            <br />

            <span id="plot_extra">
              <small>
                Type: <%= imdb_datum.flick_type.capitalize! %> <span class="separators">|</span>
                Rated: <%= imdb_datum.rating %> <span class="separators">|</span>
                Genre: <%= imdb_datum.genre %> <span class="separators">|</span>
                IMDB Rating: <%= imdb_datum.imdbrating %>
              </small>
            </span>

            <br />

            <div id="plot"><%= imdb_datum.plot.truncate(256, separator: ' ') %></div>
  
          </div>
      <% end %>
  <% else %>
    No matching flicks found. Feel free to <u><a href="<%= new_imdb_datum_path %>">add a flick</a></u> from the IMDB database.

  <% end %>
</div>

app/views/all_flicks/new.html.erb
<h1>New all_flick</h1>

<%= render 'form' %>

<%= link_to 'Back', all_flicks_path %>

app/views/all_flicks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_all_flick_path(@all_flick) %> |
<%= link_to 'Back', all_flicks_path %>