config/routes.rb
Myflicks::Application.routes.draw do

  get "all_flicks/index"
  get "your_flicks/index"
  get "home/index"  

  resources :all_flicks
  resources :flicks
  resources :imdb_data
  resources :your_flicks
  resources :user_comments
  devise_for :users
  resources :users

  root 'home#index'

  

end

app/models/your_flick.rb
class YourFlick < ActiveRecord::Base

end

app/controllers/your_flicks_controller.rb
class YourFlicksController < ApplicationController
  before_action :set_your_flick, only: [:show, :edit, :update, :destroy]

  # GET /your_flicks
  # GET /your_flicks.json
  def index

    if !user_signed_in?
      redirect_to root_url, notice: "You must be signed in to access other pages!"
    else
      @imdb_data = ImdbDatum.find(:all).uniq

      @flicks = Flick.all
      @flicks_data = Array.new

      @flicks.each do |f|
        if current_user.id == f.user_id
          @flicks_data.push(f)
        end
      end
      @flicks_data.reverse!
    end
  end

  # GET /your_flicks/1
  # GET /your_flicks/1.json
  def show
  end

  # GET /your_flicks/new
  def new
    @your_flick = YourFlick.new
  end

  # GET /your_flicks/1/edit
  def edit
  end

  # POST /your_flicks
  # POST /your_flicks.json
  def create
    @your_flick = YourFlick.new(your_flick_params)

    respond_to do |format|
      if @your_flick.save
        format.html { redirect_to @your_flick, notice: 'Your flick was successfully created.' }
        format.json { render action: 'show', status: :created, location: @your_flick }
      else
        format.html { render action: 'new' }
        format.json { render json: @your_flick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /your_flicks/1
  # PATCH/PUT /your_flicks/1.json
  def update
    respond_to do |format|
      if @your_flick.update(your_flick_params)
        format.html { redirect_to @your_flick, notice: 'Your flick was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @your_flick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /your_flicks/1
  # DELETE /your_flicks/1.json
  def destroy
    @your_flick.destroy

    respond_to do |format|
      format.html { redirect_to your_flicks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_your_flick
      @your_flick = YourFlick.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def your_flick_params
      params[:your_flick]
    end
end

app/helpers/your_flicks_helper.rb
module YourFlicksHelper
end

app/views/your_flicks/_form.html.erb
<%= form_for(@your_flick) do |f| %>
  <% if @your_flick.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@your_flick.errors.count, "error") %> prohibited this your_flick from being saved:</h2>

      <ul>
      <% @your_flick.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/your_flicks/edit.html.erb
<h1>Editing your_flick</h1>

<%= render 'form' %>

<%= link_to 'Show', @your_flick %> |
<%= link_to 'Back', your_flicks_path %>

app/views/your_flicks/index.html.erb
<br />
<br />
<span class="sub_heading">Your Flicks (<%= @flicks_data.count %>)</span>

<br />
<br />

  <% @flicks_data.each do |flick| %>
    <% @imdb_data.each do |imdb_datum| %>
      <% if flick.imdb_id == imdb_datum.imdb_id %>
        <div class="well">
          <div id="poster_index"><img src="<%= imdb_datum.poster %>" /></div>

          <div id="flick_title"><a href="<%= imdb_datum_path(imdb_datum.imdb_id) %>"><%= imdb_datum.title %> (<%= imdb_datum.year %>)</a></div>

          <div id="index_flick_options">
            <span class="icon-comment"></span>
            <% comment_count = imdb_datum.user_comments.count %>
            <span><a href="<%= imdb_datum_path(imdb_datum.imdb_id) %>#comments_section">Comments (<%= comment_count %>)</a></span>

            <br />
            <br />

            <span class="icon-remove"></span>
            <%= link_to "Remove Flick", flick, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>

          <br />
  
          <span id="plot_extra">
            <small>
              Type: <%= imdb_datum.flick_type.capitalize! %> <span class="separators">|</span>
              Rated: <%= imdb_datum.rating %> <span class="separators">|</span>
              Genre: <%= imdb_datum.genre %> <span class="separators">|</span>
              IMDB Rating: <%= imdb_datum.imdbrating %>
            </small>
          </span>

          <br />

          <div id="plot"><%= imdb_datum.plot.truncate(256, separator: ' ') %></div>
        </div>
      <% end %> <!-- flick imdb id check -->
    <% end %> <!-- imdb data each end -->
  <% end %>
<br />

app/views/your_flicks/new.html.erb
<h1>New your_flick</h1>

<%= render 'form' %>

<%= link_to 'Back', your_flicks_path %>

app/views/your_flicks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_your_flick_path(@your_flick) %> |
<%= link_to 'Back', your_flicks_path %>