config/routes.rb
Myflicks::Application.routes.draw do

  get "all_flicks/index"
  get "your_flicks/index"
  get "home/index"  

  resources :all_flicks
  resources :flicks
  resources :imdb_data
  resources :your_flicks
  resources :user_comments
  devise_for :users
  resources :users

  root 'home#index'

  

end

app/models/user_comment.rb
class UserComment < ActiveRecord::Base
  belongs_to :imdb_datum
  belongs_to :user

#  validates_presence_of :comment
end

app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController
  before_action :set_user_comment, only: [:show, :edit, :update, :destroy]

  # GET /user_comments
  # GET /user_comments.json
  def index
#    @user_comments = UserComment.all
    redirect_to root_url
  end

  # GET /user_comments/1
  # GET /user_comments/1.json
  def show
  end

  # GET /user_comments/new
  def new
    @user_comment = UserComment.new
    if params[:imdb_datum_id]
      @user_comment.user_id = current_user.id
      @user_comment.user_email = current_user.email
      @user_comment.imdb_datum_id = params[:imdb_datum_id]
    end
  end

  # GET /user_comments/1/edit
  def edit
  end

  # POST /user_comments
  # POST /user_comments.json
  def create
    @user_comment = UserComment.new(user_comment_params)

    flick_url = user_comment_params["imdb_datum_id"]

    if  user_comment_params["comment"] != nil && user_comment_params["comment"] != "" 
      if @user_comment.save
        redirect_to("/imdb_data/#{flick_url}")
      end
    else
      flash[:notice] = "You cannot post a blank comment."
      redirect_to("/imdb_data/#{flick_url}")
    end

=begin
    respond_to do |format|
      if @user_comment.save
        format.html { redirect_to @user_comment, notice: 'User comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_comment.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # PATCH/PUT /user_comments/1
  # PATCH/PUT /user_comments/1.json
  def update
      if @user_comment.update(user_comment_params)
        flick_url = user_comment_params["imdb_datum_id"]
        redirect_to("/imdb_data/#{flick_url}")
      end
=begin
    respond_to do |format|
    #    format.html { redirect_to @user_comment, notice: 'User comment was successfully updated.' }
    #    format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_comment.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # DELETE /user_comments/1
  # DELETE /user_comments/1.json
  def destroy
    @user_comment.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: "Your comment was deleted!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_comment
      @user_comment = UserComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_comment_params
      params.require(:user_comment).permit(:user_id, :user_email, :imdb_datum_id, :comment)
    end
end

app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

app/views/user_comments/_form.html.erb
<%= form_for([@imdb_data, @user_comment]) do |f| %>
  <% if @user_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_comment.errors.count, "error") %> prohibited this user_comment from being saved:</h2>

      <ul>
      <% @user_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :user_id, readonly: true %>
    <%= f.hidden_field :user_email, readonly: true %>
    <%= f.hidden_field :imdb_datum_id, readonly: true %>
  <div class="comment_box">
    <%= f.text_area :comment, placeholder: "Enter a comment here", class: "comment_box" %>
  </div>
  <div class="actions">
    <%= f.submit "Post", class: "btn btn-mini" %>
    <a href="../../imdb_data/<%= params[:imdb_datum_id] %>", class="btn btn-mini">Discard</a>
  </div>
<% end %>

app/views/user_comments/edit.html.erb
<br />
<br />
<span class="sub_heading">Enter a comment</span>
<br />
<br />

<%= render 'form' %>

app/views/user_comments/index.html.erb
<h1>Listing user_comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Imdb</th>
      <th>Comment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_comments.each do |user_comment| %>
      <tr>
        <td><%= user_comment.user_id %></td>
        <td><%= user_comment.imdb_datum_id %></td>
        <td><%= user_comment.comment %></td>
        <td><%= link_to 'Show', user_comment %></td>
        <td><%= link_to 'Edit', edit_user_comment_path(user_comment) %></td>
        <td><%= link_to 'Destroy', user_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User comment', new_user_comment_path %>

app/views/user_comments/new.html.erb
<br />
<br />
<span class="sub_heading">Enter a comment</span>
<br />
<br />

<%= render 'form' %>

app/views/user_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_comment.user_id %>
  <%= @user_comment.user_email %>
</p>

<p>
  <strong>Imdb:</strong>
  <%= @user_comment.imdb_datum_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @user_comment.comment %>
</p>

<%= link_to 'Edit', edit_user_comment_path(@user_comment) %> |
<%= link_to 'Back', user_comments_path %>