config/routes.rb
Myflicks::Application.routes.draw do

  get "all_flicks/index"
  get "your_flicks/index"
  get "home/index"  

  resources :all_flicks
  resources :flicks
  resources :imdb_data
  resources :your_flicks
  resources :user_comments
  devise_for :users
  resources :users

  root 'home#index'

  

end

app/controllers/imdb_data_controller.rb
class ImdbDataController < ApplicationController
  require 'open-uri'
  require 'json'
  require 'net/http'

  before_action :set_imdb_datum, only: [:show, :edit, :update, :destroy]

  # GET /imdb_data
  # GET /imdb_data.json
  def index
#    @imdb_data = ImdbDatum.all
    redirect_to root_url
  end

  # GET /imdb_data/1
  # GET /imdb_data/1.json
  def show
  end

  # GET /imdb_data/new
  def new
    @imdb_datum = ImdbDatum.new
  end

  # GET /imdb_data/1/edit
  def edit
  end

  # POST /imdb_data
  # POST /imdb_data.json
  def create
    @imdb_datum = ImdbDatum.new(imdb_datum_params) # New movie entry
    imdb_value = imdb_datum_params["imdb_id"] # Movie title or IMDB id from the form

    if imdb_value.match(/tt+\d*/)
     url = URI.escape("http://www.omdbapi.com/?i=#{imdb_value}&plot=short")
    else
      url = URI.escape("http://www.omdbapi.com/?t=#{imdb_value}&plot=short")
    end

    buffer = open(url, "UserAgent" => "Ruby-Wget").read
    result = JSON.parse(buffer) # Parse JSON data to Hash

    if result["Response"] == "False"
      redirect_to new_imdb_datum_path, notice: "Incorrect title or ID. Please try again with a valid value."
    else

      unique_id = SecureRandom.hex # Unique ID binding the flick with the IMDB data
      @flick = Flick.new
      @flick.unique_id = unique_id
      @flick.user_id = current_user.id
      @flick.imdb_id = result["imdbID"]
      @flick.save

      if result["Poster"] == "N/A"
        imgur_link = "http://i.imgur.com/DTlIlng.png"
      else
        img = `curl --header "Authorization: Client-ID 7b8479c28beaf08" https://api.imgur.com/3/upload/?image=#{result["Poster"]}&type=URL`
        imgur_link = JSON.parse(img)["data"]["link"]
      end

      @imdb_datum.unique_id = unique_id
      @imdb_datum.imdb_id = result["imdbID"]
      @imdb_datum.title = result["Title"]
      @imdb_datum.year = result["Year"]
      @imdb_datum.release_date = result["Released"]
      @imdb_datum.runtime = result["Runtime"]
      @imdb_datum.genre = result["Genre"]
      @imdb_datum.rating = result["Rated"]
      @imdb_datum.imdbrating = result["imdbRating"]
      @imdb_datum.poster = imgur_link
      @imdb_datum.plot = result["Plot"]
      @imdb_datum.flick_type = result["Type"]
      @imdb_datum.director = result["Director"]
      @imdb_datum.writer = result["Writer"]
      @imdb_datum.actors = result["Actors"]
      @imdb_datum.save

      if @flick.save && @imdb_datum.save
        redirect_to your_flicks_path, notice: "#{@imdb_datum.title} (#{@imdb_datum.year}) was successfully added."
      else
        render 'new'
      end
    end

=begin
    respond_to do |format|
      if @imdb_datum.save
        format.html { redirect_to @imdb_datum, notice: '#{@imdb_datum.title} (#{@imdb.datum.year}) was successfully added.' }
        format.json { render action: 'show', status: :created, location: @imdb_datum }
      else
        format.html { render action: 'new' }
        format.json { render json: @imdb_datum.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # PATCH/PUT /imdb_data/1
  # PATCH/PUT /imdb_data/1.json
  def update
    respond_to do |format|
      if @imdb_datum.update(imdb_datum_params)
        format.html { redirect_to @imdb_datum, notice: 'Imdb datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @imdb_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imdb_data/1
  # DELETE /imdb_data/1.json
  def destroy
    @imdb_datum.destroy
    respond_to do |format|
      format.html { redirect_to imdb_data_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imdb_datum
      @imdb_datum = ImdbDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imdb_datum_params
      params.require(:imdb_datum).permit(:imdb_id)
    end
end

app/helpers/imdb_data_helper.rb
module ImdbDataHelper
end

app/views/imdb_data/_form.html.erb
<%= form_for(@imdb_datum) do |f| %>
  <% if @imdb_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@imdb_datum.errors.count, "error") %> prohibited this imdb_datum from being saved:</h2>

      <ul>
      <% @imdb_datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="well">
  <div class="field">
    <%= f.label :imdb_id, "Enter a title or IMDB Id" %> 
    <%= f.text_field :imdb_id, autofocus: true %>
    <br />
    <%= f.submit id="Add", class:"btn" %>
  </div>
</div>
<% end %>

app/views/imdb_data/edit.html.erb
<h1>Editing imdb_datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @imdb_datum %> |
<%= link_to 'Back', imdb_data_path %>

app/views/imdb_data/index.html.erb
<h1>Listing imdb_data</h1>

<table>
  <thead>
    <tr>
      <th>Imdb</th>
      <th>Title</th>
      <th>Year</th>
      <th>Release date</th>
      <th>Runtime</th>
      <th>Genre</th>
      <th>Plot</th>
      <th>Poster</th>
      <th>Rating</th>
      <th>Type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @imdb_data.each do |imdb_datum| %>
      <tr>
        <td><%= imdb_datum.imdb_id %></td>
        <td><%= imdb_datum.title %></td>
        <td><%= imdb_datum.year %></td>
        <td><%= imdb_datum.release_date %></td>
        <td><%= imdb_datum.runtime %></td>
        <td><%= imdb_datum.genre %></td>
        <td><%= imdb_datum.plot %></td>
        <td><%= imdb_datum.poster %></td>
        <td><%= imdb_datum.rating %></td>
        <td><%= imdb_datum.flick_type %></td>
        <td><%= link_to 'Show', imdb_datum %></td>
        <td><%= link_to 'Edit', edit_imdb_datum_path(imdb_datum) %></td>
        <td><%= link_to 'Destroy', imdb_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Imdb datum', new_imdb_datum_path %>

app/views/imdb_data/new.html.erb
<br />
<br />
<span class="sub_heading">Add a Flick</span>
<br />
<br />

<%= render 'form' %>
<br />

app/views/imdb_data/show.html.erb
<br />
<div id="show_poster">
  <img src="<%= @imdb_datum.poster %>" />
</div>
 
<br />
<span class="show_heading"><%= @imdb_datum.title %></span>
<br />
<br />
  
<div id="show_flick">
<p>
  <strong>Type:</strong>
  <%= @imdb_datum.flick_type.capitalize %>
</p>

<p>
  <strong>Year:</strong>
  <%= @imdb_datum.year %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @imdb_datum.release_date %>
</p>

<p>
  <strong>Runtime:</strong>
  <%= @imdb_datum.runtime %>
</p>

<p>
  <strong>Plot:</strong>
  <%= @imdb_datum.plot %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @imdb_datum.genre %>
</p>

<p>
  <strong>Director(s):</strong>
  <%= @imdb_datum.director %>
</p>

<p>
  <strong>Actor(s):</strong>
  <%= @imdb_datum.actors %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @imdb_datum.rating %>
</p>

<p>
  <strong>IMDB Rating:</strong>
  <%= @imdb_datum.imdbrating %>
</p>

</div>

<br />
<br />
<br />
<br />
<% comment_count = @imdb_datum.user_comments.count %>
<span class="sub_heading">Comments (<%= comment_count %>)</span>
<a href="#comments_section" />
 <div id="add_comment">
    <%= link_to 'Add a comment', new_user_comment_path(:imdb_datum_id => @imdb_datum.imdb_id), class: "btn btn-small" %>
  </div> 
<br />
<br />
<% if comment_count > 0 %>
  <% @imdb_datum.user_comments.each do |com| %>
    <div class="user_comments well">
      <strong><%= com.user_email.split('@')[0] %></strong>: <%= com.comment %>
      <% if current_user.id == com.user_id %>
        <span class="comment_options">
          <%= link_to '', edit_user_comment_path(com, :imdb_datum_id => @imdb_datum.imdb_id), class: "icon-pencil" %>
          <%= link_to '', com, method: :delete, data: { confirm: 'Are you sure?' }, class: "icon-remove" %>
        </span>
     <% end %>
    </div>
  <% end %>
<% else %>
  No comments posted yet!
<% end %>

<br />
<br />
<br />